- task: AzureCLI@2
  inputs:
    azureSubscription: 'connectwithazure'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list'
trigger:
-none

pool:
  vmImage: ubuntu-latest

steps:

